name: 更新 mihomo 规则

on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"

concurrency:
  group: update-rules
  cancel-in-progress: false

jobs:
  update-rules:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: ./dev/curl-rule.sh
      - run: ./dev/process-rule.sh
      - run: ./dev/git-push.sh
