name: mihomo-rule-name
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"
jobs:
  mihomo-rule-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run scripts
        run: |
          bash dev/download_tmp_rule.sh
          bash dev/processing_rules.sh
          bash dev/push.sh
