name: mihomo-rule-name
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"
jobs:
  mihomo-rule-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run scripts
        run: |
          dev/download_tmp_rule.sh
          dev/processing_rules.sh
          dev/push.sh
